# Generated by Django 3.2.6 on 2021-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210812_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricetype',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Sale', 'Sale'), ('Limited', 'Limited')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
