# Generated by Django 3.2.6 on 2021-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210816_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='headerimg',
            field=models.ImageField(blank=True, default='Suprise.png', null=True, upload_to='static/images'),
        ),
    ]
