# Generated by Django 3.2.6 on 2021-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_category_headerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='headerimg',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
