# Generated by Django 3.2.6 on 2021-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210817_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='headerimg',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
